### ISSUE TITLE
Enter doesn't work in terminal if the terminal is started quickly after boot

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#361]
I have observed that pressing enter in a terminal still requires the weird "ctrl+enter" hack, but only if you start a terminal early in the boot process.

Perhaps it is started before hildon-input-method or something.

**Comment by SimonIremonger** [comment]
This sounds like issue 2 within Bug #316 ...  as per @spinal84.
Fundamentally there is this history swapping enter/kp_enter KEY_RETURN <> KEY_ENTER in x11 (something like that) mechanic going on in hildon that needs taking out, as per the start of bug #316.

**Comment by SimonIremonger** [comment]
I'm starting to suspect there is a further complexity nobody has quite recognized yet ... what is clear talking to 'danels' who was involved in maemo days, is that the spec was broken back to the beginning, and left a confusion-minefield behind in the wake.....

**Comment by MerlijnWajer** [comment]
AFAIK the bug mostly has been fixed, and this is likely just a race between xterm and hildon-input-method starting?

**Comment by SimonIremonger** [comment]
I (thought) it had not been sorted, on all 3 grounds.
NB:  Please test the "less" (or "tf5") (as described in #316).. Last I saw enter/return problem still existed (NB: more subtle than pressing enter in bash prompt).
Clearly, the issue with terminal soon on startup is not fixed.
The unknowns about VKB popup keys, are not answered that I know about ...

**Comment by MerlijnWajer** [comment]
Well, this issue is about a specific problem.

vkb keys work fine for me on n900, and we have a pretty decent idea on how to solve it on the droid 4.

**Comment by SimonIremonger** [comment]
This bug is believed to be fixed in current leste beowulf-devel...

Reportedly from IRC "the reason for this was that libhim applications didn't process enter at all, then instead just sent enter to him which just sent enter back via a hildon only interface".  In any case the problem is not happening for me now, keys in osso-xterm and xterm on n900 are now working fine, for me =).

**Comment by parazyd** [comment]
Fixed, I built xkb-data for main as well.
