### ISSUE TITLE
N900: Linux6.1: No booting on last update.

### ISSUE THREAD

**Issue by carlosgonz0** [maemo-leste/bugtracker#681]
I have the devel repos enabled on N900 plus U-boot 2021 permanent.
Linux 5.18 worked fine, but with last update to upgrade to Linux6.1 the N900 not boot. 
Just reporting.. . ..

**Comment by IMbackK** [comment]
Hi
yeah we are aware, the n900's modem is currently broken and preventing boot in the devel branch. to get your device back you have to mount the sdcard and blacklist the modem or move the ofono init script

**Comment by carlosgonz0** [comment]
Thanks  and i hope  the modem and audio get fixed soon too for N900. Sadly the modem firmware for Droid 4 seems blocked in USA, so i troubleshooting a way to get it working.

**Comment by carlosgonz0** [comment]
I tested now, and the n900still hang. :  (

**Comment by IMbackK** [comment]
could you check if 
/etc/modules-load.d/nokia-modem.conf and
/etc/modprobe.d/blacklist-omap-ssi.conf
exist on your system?

**Comment by IMbackK** [comment]
thanks

**Comment by carlosgonz0** [comment]
I get  booting the n900 by deleting modules-load.d folder.

**Comment by sicelo** [comment]
> Also seems there is issues for charging in linux 6.1

What kind of issues?

**Comment by carlosgonz0** [comment]
> > Also seems there is issues for charging in linux 6.1
> 
> What kind of issues?

The N900 do not get charging under 6.1 i not sure if it is that i deleted the whole modules-load.d directory.

**Comment by sicelo** [comment]
please share output of `ls /sys/class/udc/` and `ls /sys/class/power_supply/`

**Comment by carlosgonz0** [comment]
Devuan GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Dec  8 01:46:00 2022 from 10.0.0.82
user@devuan-n900:~$ ls /sys/class/udc/
user@devuan-n900:~$ ls /sys/class/power_supply/
bq24150a-0  bq27000-battery  bq27200-0  twl4030_ac  twl4030_usb
user@devuan-n900:~$ sudo ls /sys/class/udc/
user@devuan-n900:~$

**Comment by sicelo** [comment]
please `apt upgrade`, then report back if there is still a charging issue. it should already be resolved

**Comment by carlosgonz0** [comment]
I did an apt upgrade 2 day ago and today i did another apt upgrade, and still the same issue, like can not get charging.
So i will test again when Maemo Chimaera it out for N900.

**Comment by sicelo** [comment]
that sounds bad. unfortunately my leste sd card is a bit broken atm, and
i won't have time to look at it for at least a week.

in the meantime, to get charging, you can do:

~$ echo 'host' | sudo tee /sys/class/power_supply/bq24150a/mode         # sets current limit to 500mA
~$ echo 'dedicated' | sudo tee /sys/class/power_supply/bq24150a/mode    # sets current limit to 1800mA

Naturally, choose 'dedicated' only when connected to a wall charger, NOT
USB port on, e.g. PC.

When done charging, do:

~$ echo 'auto' | sudo tee /sys/class/power_supply/bq24150a/mode    # sets current limit to 100mA (default)

**Comment by MerlijnWajer** [comment]
The latest kernel in maemo/beowulf-devel has at least have this modem problem fixed.

**Comment by sicelo** [comment]
charging issue is also fixed as of today in beowulf-devel

**Comment by carlosgonz0** [comment]
Thanks sincelo ,merlijn.
